.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

########
# Role #
########

ROLE               = manala.apache
ROLE_DISTRIBUTIONS = debian.wheezy debian.jessie debian.stretch
